(cl:defpackage uuv_sensor_ros_plugins_msgs-msg
  (:use )
  (:export
   "<ACOUSTICRANGETWTT>"
   "ACOUSTICRANGETWTT"
   "<ACOUSTICTXREQUEST>"
   "ACOUSTICTXREQUEST"
   "<CHEMICALPARTICLECONCENTRATION>"
   "CHEMICALPARTICLECONCENTRATION"
   "<DVL>"
   "DVL"
   "<DVLBEAM>"
   "DVLBEAM"
   "<POSITIONWITHCOVARIANCE>"
   "POSITIONWITHCOVARIANCE"
   "<POSITIONWITHCOVARIANCESTAMPED>"
   "POSITIONWITHCOVARIANCESTAMPED"
   "<SALINITY>"
   "SALINITY"
  ))

