# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uuv_sensor_ros_plugins_msgs/AcousticRangeOWTT.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import std_msgs.msg
import uuv_sensor_ros_plugins_msgs.msg

class AcousticRangeOWTT(genpy.Message):
  _md5sum = "8215537df9cb58042c7c2090621e64e6"
  _type = "uuv_sensor_ros_plugins_msgs/AcousticRangeOWTT"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string from_ns
string to_ns
# Transmit time at sender and receive time at receiver (ROS sim time)
time t_tx
time t_rx

# One-way measured range (meters) and its variance
float64 range
float64 variance

# Transmitter's position estimate and covariance at t_tx
uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped tx_pos

# Cross-covariance between sender 15-dim error state and its position (15x3, row-major)
float64[45] tx_cross_cov_x_p



================================================================================
MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped
# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This expresses an estimated position with a reference coordinate frame and
# timestamp

Header header
PositionWithCovariance pos

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovariance
# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This represents a position in free space with uncertainty.

geometry_msgs/Point pos

# Row-major representation of the 3x3 covariance matrix
float64[9] covariance

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['from_ns','to_ns','t_tx','t_rx','range','variance','tx_pos','tx_cross_cov_x_p']
  _slot_types = ['string','string','time','time','float64','float64','uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped','float64[45]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       from_ns,to_ns,t_tx,t_rx,range,variance,tx_pos,tx_cross_cov_x_p

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AcousticRangeOWTT, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.from_ns is None:
        self.from_ns = ''
      if self.to_ns is None:
        self.to_ns = ''
      if self.t_tx is None:
        self.t_tx = genpy.Time()
      if self.t_rx is None:
        self.t_rx = genpy.Time()
      if self.range is None:
        self.range = 0.
      if self.variance is None:
        self.variance = 0.
      if self.tx_pos is None:
        self.tx_pos = uuv_sensor_ros_plugins_msgs.msg.PositionWithCovarianceStamped()
      if self.tx_cross_cov_x_p is None:
        self.tx_cross_cov_x_p = [0.] * 45
    else:
      self.from_ns = ''
      self.to_ns = ''
      self.t_tx = genpy.Time()
      self.t_rx = genpy.Time()
      self.range = 0.
      self.variance = 0.
      self.tx_pos = uuv_sensor_ros_plugins_msgs.msg.PositionWithCovarianceStamped()
      self.tx_cross_cov_x_p = [0.] * 45

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.from_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.to_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I2d3I().pack(_x.t_tx.secs, _x.t_tx.nsecs, _x.t_rx.secs, _x.t_rx.nsecs, _x.range, _x.variance, _x.tx_pos.header.seq, _x.tx_pos.header.stamp.secs, _x.tx_pos.header.stamp.nsecs))
      _x = self.tx_pos.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.tx_pos.pos.pos.x, _x.tx_pos.pos.pos.y, _x.tx_pos.pos.pos.z))
      buff.write(_get_struct_9d().pack(*self.tx_pos.pos.covariance))
      buff.write(_get_struct_45d().pack(*self.tx_cross_cov_x_p))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t_tx is None:
        self.t_tx = genpy.Time()
      if self.t_rx is None:
        self.t_rx = genpy.Time()
      if self.tx_pos is None:
        self.tx_pos = uuv_sensor_ros_plugins_msgs.msg.PositionWithCovarianceStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.from_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.from_ns = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.to_ns = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.t_tx.secs, _x.t_tx.nsecs, _x.t_rx.secs, _x.t_rx.nsecs, _x.range, _x.variance, _x.tx_pos.header.seq, _x.tx_pos.header.stamp.secs, _x.tx_pos.header.stamp.nsecs,) = _get_struct_4I2d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tx_pos.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tx_pos.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.tx_pos.pos.pos.x, _x.tx_pos.pos.pos.y, _x.tx_pos.pos.pos.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.tx_pos.pos.covariance = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 360
      self.tx_cross_cov_x_p = _get_struct_45d().unpack(str[start:end])
      self.t_tx.canon()
      self.t_rx.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.from_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.to_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I2d3I().pack(_x.t_tx.secs, _x.t_tx.nsecs, _x.t_rx.secs, _x.t_rx.nsecs, _x.range, _x.variance, _x.tx_pos.header.seq, _x.tx_pos.header.stamp.secs, _x.tx_pos.header.stamp.nsecs))
      _x = self.tx_pos.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.tx_pos.pos.pos.x, _x.tx_pos.pos.pos.y, _x.tx_pos.pos.pos.z))
      buff.write(self.tx_pos.pos.covariance.tostring())
      buff.write(self.tx_cross_cov_x_p.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t_tx is None:
        self.t_tx = genpy.Time()
      if self.t_rx is None:
        self.t_rx = genpy.Time()
      if self.tx_pos is None:
        self.tx_pos = uuv_sensor_ros_plugins_msgs.msg.PositionWithCovarianceStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.from_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.from_ns = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.to_ns = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.t_tx.secs, _x.t_tx.nsecs, _x.t_rx.secs, _x.t_rx.nsecs, _x.range, _x.variance, _x.tx_pos.header.seq, _x.tx_pos.header.stamp.secs, _x.tx_pos.header.stamp.nsecs,) = _get_struct_4I2d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tx_pos.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tx_pos.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.tx_pos.pos.pos.x, _x.tx_pos.pos.pos.y, _x.tx_pos.pos.pos.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.tx_pos.pos.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 360
      self.tx_cross_cov_x_p = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=45)
      self.t_tx.canon()
      self.t_rx.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_45d = None
def _get_struct_45d():
    global _struct_45d
    if _struct_45d is None:
        _struct_45d = struct.Struct("<45d")
    return _struct_45d
_struct_4I2d3I = None
def _get_struct_4I2d3I():
    global _struct_4I2d3I
    if _struct_4I2d3I is None:
        _struct_4I2d3I = struct.Struct("<4I2d3I")
    return _struct_4I2d3I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
