# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uuv_sensor_ros_plugins_msgs/AcousticRangeTWTT.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import std_msgs.msg

class AcousticRangeTWTT(genpy.Message):
  _md5sum = "998a5403ceadaee45594f77aee3f1e98"
  _type = "uuv_sensor_ros_plugins_msgs/AcousticRangeTWTT"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# From initiator namespace to responder namespace
string from_ns
string to_ns
# Time stamps in ROS time (sim time)
time t0
# arrival time at responder (unknown to initiator; for logging)
time t1
# arrival time of reply at initiator
time t2
# Measured r1 = || p1(t2) - p2(t1) || (delta assumed 0 in minimal version)
float64 r1
# Peer pose at t1 (as provided by responder)
geometry_msgs/PoseStamped peer_pose_t1
# Success flag and variance of r1
bool success
float64 variance

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['from_ns','to_ns','t0','t1','t2','r1','peer_pose_t1','success','variance']
  _slot_types = ['string','string','time','time','time','float64','geometry_msgs/PoseStamped','bool','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       from_ns,to_ns,t0,t1,t2,r1,peer_pose_t1,success,variance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AcousticRangeTWTT, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.from_ns is None:
        self.from_ns = ''
      if self.to_ns is None:
        self.to_ns = ''
      if self.t0 is None:
        self.t0 = genpy.Time()
      if self.t1 is None:
        self.t1 = genpy.Time()
      if self.t2 is None:
        self.t2 = genpy.Time()
      if self.r1 is None:
        self.r1 = 0.
      if self.peer_pose_t1 is None:
        self.peer_pose_t1 = geometry_msgs.msg.PoseStamped()
      if self.success is None:
        self.success = False
      if self.variance is None:
        self.variance = 0.
    else:
      self.from_ns = ''
      self.to_ns = ''
      self.t0 = genpy.Time()
      self.t1 = genpy.Time()
      self.t2 = genpy.Time()
      self.r1 = 0.
      self.peer_pose_t1 = geometry_msgs.msg.PoseStamped()
      self.success = False
      self.variance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.from_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.to_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6Id3I().pack(_x.t0.secs, _x.t0.nsecs, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs, _x.r1, _x.peer_pose_t1.header.seq, _x.peer_pose_t1.header.stamp.secs, _x.peer_pose_t1.header.stamp.nsecs))
      _x = self.peer_pose_t1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dBd().pack(_x.peer_pose_t1.pose.position.x, _x.peer_pose_t1.pose.position.y, _x.peer_pose_t1.pose.position.z, _x.peer_pose_t1.pose.orientation.x, _x.peer_pose_t1.pose.orientation.y, _x.peer_pose_t1.pose.orientation.z, _x.peer_pose_t1.pose.orientation.w, _x.success, _x.variance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t0 is None:
        self.t0 = genpy.Time()
      if self.t1 is None:
        self.t1 = genpy.Time()
      if self.t2 is None:
        self.t2 = genpy.Time()
      if self.peer_pose_t1 is None:
        self.peer_pose_t1 = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.from_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.from_ns = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.to_ns = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.t0.secs, _x.t0.nsecs, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs, _x.r1, _x.peer_pose_t1.header.seq, _x.peer_pose_t1.header.stamp.secs, _x.peer_pose_t1.header.stamp.nsecs,) = _get_struct_6Id3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.peer_pose_t1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.peer_pose_t1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 65
      (_x.peer_pose_t1.pose.position.x, _x.peer_pose_t1.pose.position.y, _x.peer_pose_t1.pose.position.z, _x.peer_pose_t1.pose.orientation.x, _x.peer_pose_t1.pose.orientation.y, _x.peer_pose_t1.pose.orientation.z, _x.peer_pose_t1.pose.orientation.w, _x.success, _x.variance,) = _get_struct_7dBd().unpack(str[start:end])
      self.success = bool(self.success)
      self.t0.canon()
      self.t1.canon()
      self.t2.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.from_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.to_ns
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6Id3I().pack(_x.t0.secs, _x.t0.nsecs, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs, _x.r1, _x.peer_pose_t1.header.seq, _x.peer_pose_t1.header.stamp.secs, _x.peer_pose_t1.header.stamp.nsecs))
      _x = self.peer_pose_t1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dBd().pack(_x.peer_pose_t1.pose.position.x, _x.peer_pose_t1.pose.position.y, _x.peer_pose_t1.pose.position.z, _x.peer_pose_t1.pose.orientation.x, _x.peer_pose_t1.pose.orientation.y, _x.peer_pose_t1.pose.orientation.z, _x.peer_pose_t1.pose.orientation.w, _x.success, _x.variance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t0 is None:
        self.t0 = genpy.Time()
      if self.t1 is None:
        self.t1 = genpy.Time()
      if self.t2 is None:
        self.t2 = genpy.Time()
      if self.peer_pose_t1 is None:
        self.peer_pose_t1 = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.from_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.from_ns = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_ns = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.to_ns = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.t0.secs, _x.t0.nsecs, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs, _x.r1, _x.peer_pose_t1.header.seq, _x.peer_pose_t1.header.stamp.secs, _x.peer_pose_t1.header.stamp.nsecs,) = _get_struct_6Id3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.peer_pose_t1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.peer_pose_t1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 65
      (_x.peer_pose_t1.pose.position.x, _x.peer_pose_t1.pose.position.y, _x.peer_pose_t1.pose.position.z, _x.peer_pose_t1.pose.orientation.x, _x.peer_pose_t1.pose.orientation.y, _x.peer_pose_t1.pose.orientation.z, _x.peer_pose_t1.pose.orientation.w, _x.success, _x.variance,) = _get_struct_7dBd().unpack(str[start:end])
      self.success = bool(self.success)
      self.t0.canon()
      self.t1.canon()
      self.t2.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6Id3I = None
def _get_struct_6Id3I():
    global _struct_6Id3I
    if _struct_6Id3I is None:
        _struct_6Id3I = struct.Struct("<6Id3I")
    return _struct_6Id3I
_struct_7dBd = None
def _get_struct_7dBd():
    global _struct_7dBd
    if _struct_7dBd is None:
        _struct_7dBd = struct.Struct("<7dBd")
    return _struct_7dBd
