// Generated by gencpp from file uuv_sensor_ros_plugins_msgs/AcousticRangeOWTT.msg
// DO NOT EDIT!


#ifndef UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICRANGEOWTT_H
#define UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICRANGEOWTT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped.h>

namespace uuv_sensor_ros_plugins_msgs
{
template <class ContainerAllocator>
struct AcousticRangeOWTT_
{
  typedef AcousticRangeOWTT_<ContainerAllocator> Type;

  AcousticRangeOWTT_()
    : from_ns()
    , to_ns()
    , t_tx()
    , t_rx()
    , range(0.0)
    , variance(0.0)
    , tx_pos()
    , tx_cross_cov_x_p()  {
      tx_cross_cov_x_p.assign(0.0);
  }
  AcousticRangeOWTT_(const ContainerAllocator& _alloc)
    : from_ns(_alloc)
    , to_ns(_alloc)
    , t_tx()
    , t_rx()
    , range(0.0)
    , variance(0.0)
    , tx_pos(_alloc)
    , tx_cross_cov_x_p()  {
  (void)_alloc;
      tx_cross_cov_x_p.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _from_ns_type;
  _from_ns_type from_ns;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _to_ns_type;
  _to_ns_type to_ns;

   typedef ros::Time _t_tx_type;
  _t_tx_type t_tx;

   typedef ros::Time _t_rx_type;
  _t_rx_type t_rx;

   typedef double _range_type;
  _range_type range;

   typedef double _variance_type;
  _variance_type variance;

   typedef  ::uuv_sensor_ros_plugins_msgs::PositionWithCovarianceStamped_<ContainerAllocator>  _tx_pos_type;
  _tx_pos_type tx_pos;

   typedef boost::array<double, 45>  _tx_cross_cov_x_p_type;
  _tx_cross_cov_x_p_type tx_cross_cov_x_p;





  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> const> ConstPtr;

}; // struct AcousticRangeOWTT_

typedef ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<std::allocator<void> > AcousticRangeOWTT;

typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT > AcousticRangeOWTTPtr;
typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT const> AcousticRangeOWTTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator2> & rhs)
{
  return lhs.from_ns == rhs.from_ns &&
    lhs.to_ns == rhs.to_ns &&
    lhs.t_tx == rhs.t_tx &&
    lhs.t_rx == rhs.t_rx &&
    lhs.range == rhs.range &&
    lhs.variance == rhs.variance &&
    lhs.tx_pos == rhs.tx_pos &&
    lhs.tx_cross_cov_x_p == rhs.tx_cross_cov_x_p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_sensor_ros_plugins_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8215537df9cb58042c7c2090621e64e6";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8215537df9cb5804ULL;
  static const uint64_t static_value2 = 0x2c7c2090621e64e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_sensor_ros_plugins_msgs/AcousticRangeOWTT";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string from_ns\n"
"string to_ns\n"
"# Transmit time at sender and receive time at receiver (ROS sim time)\n"
"time t_tx\n"
"time t_rx\n"
"\n"
"# One-way measured range (meters) and its variance\n"
"float64 range\n"
"float64 variance\n"
"\n"
"# Transmitter's position estimate and covariance at t_tx\n"
"uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped tx_pos\n"
"\n"
"# Cross-covariance between sender 15-dim error state and its position (15x3, row-major)\n"
"float64[45] tx_cross_cov_x_p\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This expresses an estimated position with a reference coordinate frame and\n"
"# timestamp\n"
"\n"
"Header header\n"
"PositionWithCovariance pos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovariance\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This represents a position in free space with uncertainty.\n"
"\n"
"geometry_msgs/Point pos\n"
"\n"
"# Row-major representation of the 3x3 covariance matrix\n"
"float64[9] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_ns);
      stream.next(m.to_ns);
      stream.next(m.t_tx);
      stream.next(m.t_rx);
      stream.next(m.range);
      stream.next(m.variance);
      stream.next(m.tx_pos);
      stream.next(m.tx_cross_cov_x_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AcousticRangeOWTT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeOWTT_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "from_ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.from_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "to_ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.to_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_tx: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t_tx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_rx: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t_rx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "variance: ";
    Printer<double>::stream(s, indent + "  ", v.variance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tx_pos: ";
    Printer< ::uuv_sensor_ros_plugins_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.tx_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tx_cross_cov_x_p: ";
    if (v.tx_cross_cov_x_p.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tx_cross_cov_x_p.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.tx_cross_cov_x_p[i]);
    }
    if (v.tx_cross_cov_x_p.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICRANGEOWTT_H
