// Generated by gencpp from file uuv_sensor_ros_plugins_msgs/AcousticTxRequest.msg
// DO NOT EDIT!


#ifndef UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICTXREQUEST_H
#define UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICTXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uuv_sensor_ros_plugins_msgs
{
template <class ContainerAllocator>
struct AcousticTxRequest_
{
  typedef AcousticTxRequest_<ContainerAllocator> Type;

  AcousticTxRequest_()
    : target_ns()
    , request_id()  {
    }
  AcousticTxRequest_(const ContainerAllocator& _alloc)
    : target_ns(_alloc)
    , request_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_ns_type;
  _target_ns_type target_ns;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_id_type;
  _request_id_type request_id;





  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AcousticTxRequest_

typedef ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<std::allocator<void> > AcousticTxRequest;

typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest > AcousticTxRequestPtr;
typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest const> AcousticTxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_ns == rhs.target_ns &&
    lhs.request_id == rhs.request_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_sensor_ros_plugins_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1b001fcc36be9a459785df486239119";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1b001fcc36be9a4ULL;
  static const uint64_t static_value2 = 0x59785df486239119ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_sensor_ros_plugins_msgs/AcousticTxRequest";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Target AUV namespace to contact (e.g., eca_a9_2)\n"
"string target_ns\n"
"# Optional request identifier for bookkeeping\n"
"string request_id\n"
;
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_ns);
      stream.next(m.request_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AcousticTxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_sensor_ros_plugins_msgs::AcousticTxRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "request_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICTXREQUEST_H
