// Generated by gencpp from file uuv_sensor_ros_plugins_msgs/AcousticRangeTWTT.msg
// DO NOT EDIT!


#ifndef UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICRANGETWTT_H
#define UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICRANGETWTT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace uuv_sensor_ros_plugins_msgs
{
template <class ContainerAllocator>
struct AcousticRangeTWTT_
{
  typedef AcousticRangeTWTT_<ContainerAllocator> Type;

  AcousticRangeTWTT_()
    : from_ns()
    , to_ns()
    , t0()
    , t1()
    , t2()
    , r1(0.0)
    , peer_pose_t1()
    , success(false)
    , variance(0.0)  {
    }
  AcousticRangeTWTT_(const ContainerAllocator& _alloc)
    : from_ns(_alloc)
    , to_ns(_alloc)
    , t0()
    , t1()
    , t2()
    , r1(0.0)
    , peer_pose_t1(_alloc)
    , success(false)
    , variance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _from_ns_type;
  _from_ns_type from_ns;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _to_ns_type;
  _to_ns_type to_ns;

   typedef ros::Time _t0_type;
  _t0_type t0;

   typedef ros::Time _t1_type;
  _t1_type t1;

   typedef ros::Time _t2_type;
  _t2_type t2;

   typedef double _r1_type;
  _r1_type r1;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _peer_pose_t1_type;
  _peer_pose_t1_type peer_pose_t1;

   typedef uint8_t _success_type;
  _success_type success;

   typedef double _variance_type;
  _variance_type variance;





  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> const> ConstPtr;

}; // struct AcousticRangeTWTT_

typedef ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<std::allocator<void> > AcousticRangeTWTT;

typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT > AcousticRangeTWTTPtr;
typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT const> AcousticRangeTWTTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator2> & rhs)
{
  return lhs.from_ns == rhs.from_ns &&
    lhs.to_ns == rhs.to_ns &&
    lhs.t0 == rhs.t0 &&
    lhs.t1 == rhs.t1 &&
    lhs.t2 == rhs.t2 &&
    lhs.r1 == rhs.r1 &&
    lhs.peer_pose_t1 == rhs.peer_pose_t1 &&
    lhs.success == rhs.success &&
    lhs.variance == rhs.variance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_sensor_ros_plugins_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "998a5403ceadaee45594f77aee3f1e98";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x998a5403ceadaee4ULL;
  static const uint64_t static_value2 = 0x5594f77aee3f1e98ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_sensor_ros_plugins_msgs/AcousticRangeTWTT";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# From initiator namespace to responder namespace\n"
"string from_ns\n"
"string to_ns\n"
"# Time stamps in ROS time (sim time)\n"
"time t0\n"
"# arrival time at responder (unknown to initiator; for logging)\n"
"time t1\n"
"# arrival time of reply at initiator\n"
"time t2\n"
"# Measured r1 = || p1(t2) - p2(t1) || (delta assumed 0 in minimal version)\n"
"float64 r1\n"
"# Peer pose at t1 (as provided by responder)\n"
"geometry_msgs/PoseStamped peer_pose_t1\n"
"# Success flag and variance of r1\n"
"bool success\n"
"float64 variance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_ns);
      stream.next(m.to_ns);
      stream.next(m.t0);
      stream.next(m.t1);
      stream.next(m.t2);
      stream.next(m.r1);
      stream.next(m.peer_pose_t1);
      stream.next(m.success);
      stream.next(m.variance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AcousticRangeTWTT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_sensor_ros_plugins_msgs::AcousticRangeTWTT_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "from_ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.from_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "to_ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.to_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t0: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t1: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t2: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "r1: ";
    Printer<double>::stream(s, indent + "  ", v.r1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peer_pose_t1: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.peer_pose_t1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "variance: ";
    Printer<double>::stream(s, indent + "  ", v.variance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICRANGETWTT_H
