// Generated by gencpp from file uuv_sensor_ros_plugins_msgs/AcousticBroadcastMethod3.msg
// DO NOT EDIT!


#ifndef UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICBROADCASTMETHOD3_H
#define UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICBROADCASTMETHOD3_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped.h>

namespace uuv_sensor_ros_plugins_msgs
{
template <class ContainerAllocator>
struct AcousticBroadcastMethod3_
{
  typedef AcousticBroadcastMethod3_<ContainerAllocator> Type;

  AcousticBroadcastMethod3_()
    : from_ns()
    , t_tx()
    , tx_pos()
    , tx_cross_cov_x_p()  {
      tx_cross_cov_x_p.assign(0.0);
  }
  AcousticBroadcastMethod3_(const ContainerAllocator& _alloc)
    : from_ns(_alloc)
    , t_tx()
    , tx_pos(_alloc)
    , tx_cross_cov_x_p()  {
  (void)_alloc;
      tx_cross_cov_x_p.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _from_ns_type;
  _from_ns_type from_ns;

   typedef ros::Time _t_tx_type;
  _t_tx_type t_tx;

   typedef  ::uuv_sensor_ros_plugins_msgs::PositionWithCovarianceStamped_<ContainerAllocator>  _tx_pos_type;
  _tx_pos_type tx_pos;

   typedef boost::array<double, 45>  _tx_cross_cov_x_p_type;
  _tx_cross_cov_x_p_type tx_cross_cov_x_p;





  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> const> ConstPtr;

}; // struct AcousticBroadcastMethod3_

typedef ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<std::allocator<void> > AcousticBroadcastMethod3;

typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3 > AcousticBroadcastMethod3Ptr;
typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3 const> AcousticBroadcastMethod3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator2> & rhs)
{
  return lhs.from_ns == rhs.from_ns &&
    lhs.t_tx == rhs.t_tx &&
    lhs.tx_pos == rhs.tx_pos &&
    lhs.tx_cross_cov_x_p == rhs.tx_cross_cov_x_p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_sensor_ros_plugins_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70dd1eca161b3868442784556a528226";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70dd1eca161b3868ULL;
  static const uint64_t static_value2 = 0x442784556a528226ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_sensor_ros_plugins_msgs/AcousticBroadcastMethod3";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string from_ns\n"
"# Transmit time at sender (ROS sim time)\n"
"time t_tx\n"
"\n"
"# Transmitter's position estimate and covariance at t_tx\n"
"uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped tx_pos\n"
"\n"
"# Cross-covariance between transmitter 15-dim error state and its position (15x3, row-major)\n"
"float64[45] tx_cross_cov_x_p\n"
"\n"
"\n"
"================================================================================\n"
"MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This expresses an estimated position with a reference coordinate frame and\n"
"# timestamp\n"
"\n"
"Header header\n"
"PositionWithCovariance pos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovariance\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This represents a position in free space with uncertainty.\n"
"\n"
"geometry_msgs/Point pos\n"
"\n"
"# Row-major representation of the 3x3 covariance matrix\n"
"float64[9] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_ns);
      stream.next(m.t_tx);
      stream.next(m.tx_pos);
      stream.next(m.tx_cross_cov_x_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AcousticBroadcastMethod3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_sensor_ros_plugins_msgs::AcousticBroadcastMethod3_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "from_ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.from_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_tx: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t_tx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tx_pos: ";
    Printer< ::uuv_sensor_ros_plugins_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.tx_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tx_cross_cov_x_p: ";
    if (v.tx_cross_cov_x_p.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tx_cross_cov_x_p.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.tx_cross_cov_x_p[i]);
    }
    if (v.tx_cross_cov_x_p.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_ACOUSTICBROADCASTMETHOD3_H
