// Generated by gencpp from file uuv_sensor_ros_plugins_msgs/Method3SenderState.msg
// DO NOT EDIT!


#ifndef UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_METHOD3SENDERSTATE_H
#define UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_METHOD3SENDERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped.h>

namespace uuv_sensor_ros_plugins_msgs
{
template <class ContainerAllocator>
struct Method3SenderState_
{
  typedef Method3SenderState_<ContainerAllocator> Type;

  Method3SenderState_()
    : header()
    , ns()
    , pos()
    , cross_cov_x_p()  {
      cross_cov_x_p.assign(0.0);
  }
  Method3SenderState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ns(_alloc)
    , pos(_alloc)
    , cross_cov_x_p()  {
  (void)_alloc;
      cross_cov_x_p.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ns_type;
  _ns_type ns;

   typedef  ::uuv_sensor_ros_plugins_msgs::PositionWithCovarianceStamped_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef boost::array<double, 45>  _cross_cov_x_p_type;
  _cross_cov_x_p_type cross_cov_x_p;





  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> const> ConstPtr;

}; // struct Method3SenderState_

typedef ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<std::allocator<void> > Method3SenderState;

typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::Method3SenderState > Method3SenderStatePtr;
typedef boost::shared_ptr< ::uuv_sensor_ros_plugins_msgs::Method3SenderState const> Method3SenderStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ns == rhs.ns &&
    lhs.pos == rhs.pos &&
    lhs.cross_cov_x_p == rhs.cross_cov_x_p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator1> & lhs, const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_sensor_ros_plugins_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76191afa343ce0995d28537435cdb145";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76191afa343ce099ULL;
  static const uint64_t static_value2 = 0x5d28537435cdb145ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_sensor_ros_plugins_msgs/Method3SenderState";
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string ns\n"
"uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped pos\n"
"float64[45] cross_cov_x_p\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovarianceStamped\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This expresses an estimated position with a reference coordinate frame and\n"
"# timestamp\n"
"\n"
"Header header\n"
"PositionWithCovariance pos\n"
"\n"
"================================================================================\n"
"MSG: uuv_sensor_ros_plugins_msgs/PositionWithCovariance\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This represents a position in free space with uncertainty.\n"
"\n"
"geometry_msgs/Point pos\n"
"\n"
"# Row-major representation of the 3x3 covariance matrix\n"
"float64[9] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ns);
      stream.next(m.pos);
      stream.next(m.cross_cov_x_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Method3SenderState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_sensor_ros_plugins_msgs::Method3SenderState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos: ";
    Printer< ::uuv_sensor_ros_plugins_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cross_cov_x_p: ";
    if (v.cross_cov_x_p.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.cross_cov_x_p.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.cross_cov_x_p[i]);
    }
    if (v.cross_cov_x_p.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_SENSOR_ROS_PLUGINS_MSGS_MESSAGE_METHOD3SENDERSTATE_H
